CREATE DATABASE IF NOT EXISTS Prova;
USE Prova;

DROP TABLE IF EXISTS Persona;

CREATE TABLE Persona (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL
);
